---
title: "Iris - Machine Learning"
author: Sehuyn Hong(sese0733@naver.com)
date: "`r format(Sys.Date())`" 
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes    
  pdf_document:
    extra_dependencies: ["kotex"]
    fig_height: 6
    fig_width: 10
    toc: yes
    toc_depth: 3
  word_document:
    fig_height: 6
    fig_width: 10
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, message=F, warning=F, fig.height = 8, cache=T, dpi = 300, dev = "png")
library(tidyverse)
library(xgboost)
library(vip)
library(randomForest)
library(ggplot2)
```



# 1. 데이터 불러오기
```{r}
data("iris")
iris
View(iris)
```

## 데이터 확인
```{r}
head(iris)
tail(iris)
summary(iris)
str(iris)
dim(iris)
```

# 2. 전처리

## 결측치 확인
```{r}
sum(is.na(iris))
```

# 3. 머신러닝

## 데이터 분리
```{r}
set.seed(42)

sample <- sample.int(n = nrow(iris),
                     size = floor(.8 * nrow(iris)),
                     replace = F)
train <- iris[sample,]
test <- iris[-sample,]
```


## 모델 설계
### 랜덤 포레스트 - 중요 변수값 확인
```{r}
#install.packages("randomForest")

names(train)
train_y = train[,'Species']
train_x = train[, names(train) != 'Species']

rf_model = randomForest(train_x, 
                        y = train_y,
                        ntree=100,
                        importance = T)
rf_model$importance
```
# 중요 변수값: Petal.Length, Petal.Width


# 4. 학습
```{r}
test_y = test[,'Species']
test_x = test[, names(test) != 'Species']



dtrain = xgb.DMatrix(data = as.matrix(train_x), label = train_y)
dtest = xgb.DMatrix(data = as.matrix(test_x), label = test_y)
watchlist = list(train=dtrain, test=dtest)

bst <- xgb.train(data = dtrain, 
                 max.depth = 8,
                 eta = 0.1,
                 nround = 100, 
                 watchlist = watchlist,
                 objective = "reg:squarederror",
                 early_stopping_rounds = 10,
                 print_every_n = 100)

```


# 5. 시각화


## 데이터 형식 변환
```{r}
iris2 <- iris %>%
  pivot_longer(cols = c(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width),
               names_to = "variable",
               values_to = "value")
```

## Box plot 생성
```{r}
ggplot(iris2, aes(x = Species, y = value, fill = Species)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free") +
  labs(x = "Species", y = "Value", fill = "Species") +
  theme_minimal()
```

